services:
  web_app:
    container_name: web_app
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - redis_cache


  postgres_db:
    container_name: postgres_db
    image: postgres
    environment:
      - POSTGRES_DB=Modern-Login_db
      - POSTGRES_USER=Modern-Login_user
      - POSTGRES_PASSWORD=root

  redis_cache:
    container_name: redis_cache
    image: redis